global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-producer'
    static_configs:
      - targets: ['kafka-producer:8000']
    metrics_path: '/metrics'

  - job_name: 'stream-processor'
    static_configs:
      - targets: ['stream-processor:8000']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
